### ISSUE TITLE
[bug] Global placeholder.

### ISSUE THREAD

**Issue by yiyoperez** [Ajneb97/ServerVariables#1]
The ServerVariables placeholder returns an [empty string](https://github.com/Ajneb97/ServerVariables/blob/7ec028521c00b30d64c461e4aa31ad9a0de14c20/src/main/java/svar/ajneb97/api/ServerVariablesExpansion.java#L45) when trying to use "globalvalue_" placeholder argument, the [if statement](https://github.com/Ajneb97/ServerVariables/blob/7ec028521c00b30d64c461e4aa31ad9a0de14c20/src/main/java/svar/ajneb97/api/ServerVariablesExpansion.java#L44) should be moved inside this [else if statement](https://github.com/Ajneb97/ServerVariables/blob/7ec028521c00b30d64c461e4aa31ad9a0de14c20/src/main/java/svar/ajneb97/api/ServerVariablesExpansion.java#L52) since this is the only placeholder argument that requires a player.

Edit: typos and wrong url line.

**Comment by Ajneb97** [comment]
I will check it!
