### ISSUE TITLE
ServerVariables Error

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ServerVariables#15]
https://pastebin.com/CGDtSF31

**Comment by KhrysAK47** [comment]
config.yml: https://pastebin.com/PuQtLim7

Running latest ServerVariables version and Paper 1.20.4

**Comment by KhrysAK47** [comment]
Here: https://pastebin.com/TjxTQmpc

Can't even update it for that player.

The plugin works fine for players that joined before on 1.19.4, but not on new players after updating to 1.20.4

**Comment by Ajneb97** [comment]
You are not sending me the complete error. With only that message I can't do anything since there are no references to the code of ServerVariables.
