### ISSUE TITLE
/svar reset <variable> all doesn't work

### ISSUE THREAD

**Issue by Rexmen1** [Ajneb97/ServerVariables#17]
/svar reset <variable> all doesn't work... try using the command see if it resets for all or just player named "all" its not working for me and resetting the data for player named "all" instead of everyone's data

**Comment by Rexmen1** [comment]
lol idk how else to explain this, just go to your test server and use the command and reset variable data of everyone... see if it works for you or not... Not working for me

**Comment by Ajneb97** [comment]
I am aware of this, the next update will have this fix.

**Comment by Rexmen1** [comment]
Its seems to work now idk what changed for me... maybe paper software or something else causing the issue... But ty
