### ISSUE TITLE
Playername and UUID problem

### ISSUE THREAD

**Issue by Tanerx** [Ajneb97/ServerVariables#18]
Hello.
I test the plugin with [MMOProfiles Proxy mode](https://gitlab.com/phoenix-dvpmt/mmoprofiles/-/wikis/Proxy-Based%20Profiles). In this plugin every profile will have different uuid and uuid are really change after the profile selected. 

Problem with ServerVariables is when adding svar to player targeting wrong uuid. This is not a bug of this plugin I'm not asking to fix. 

I'm only asking small feature; use uuid instead of playername with everywhere in the plugin. We can use MMOProfiles `%mmoprofiles_current_profile_uuid%` instead of player name to fix for us.

Thank you.

**Comment by Ajneb97** [comment]
It seems you have multiple files of ServerVariables for the same user, that must not happen or you will experience this bug.

**Comment by Tanerx** [comment]
> It seems you have multiple files of ServerVariables for the same user, that must not happen or you will experience this bug.

When using MMOProfiles this will going to happen all the time because every profile of user is a different uuid. Player select a class when join the lobby server and teleport to play server after select a profile. When join a play server player will have different uuid and every profile has is different uuid. 
![image](https://github.com/Ajneb97/ServerVariables/assets/32717109/0b7d3616-1d81-45a1-8609-4c3e550e6164)

Can you support this please ?

**Comment by Ajneb97** [comment]
That is a serious incompatibility issue of MMOProfiles. All plugins work by a player name with the corresponding uuid. The uuid is unique, so it's not possible to have multiple uuids for the same user.
