### ISSUE TITLE
MySQL is not made for server syncing.

### ISSUE THREAD

**Issue by Kudosaki** [Ajneb97/ServerVariables#19]
I suggest Redis as the means of server syncing for ServerVariables because this would allow people to sync between servers more accurately.

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/ab8f6ded-dc46-4c3d-a476-b041a9f50d9f)
Set Variable on Server A

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/9904d2b1-5315-4919-8721-c8a53095182b)
Went to Server B to check variables result is wrong.

Both are connected to the same database.

And with a brief look on the code, There seems to be nothing to update that variable when player leaves/disconnect, hence that data is most likely not possible to be viewed from Server B.

**Comment by Kudosaki** [comment]
Though realistically speaking for usage of variables in cases where player switches servers constantly, Redis would be the best option.

MySQL can work too, but you'll have to add a bunch of conditions when player leave & join the server aside from the autosaving.

And also to prevent the auto saving overriding each other as well.

**Comment by Kudosaki** [comment]
Oh, I found the variable manager area, It doesn't seems like the variables are being updated properly between servers it seems?

**Comment by Ajneb97** [comment]
The data is loaded from the database everytime they join the server.

**Comment by Kudosaki** [comment]
> The data is loaded from the database everytime they join the server.

Doesn't seem like it's doing that right now on latest release for ServerVariables.

**Comment by Ajneb97** [comment]
If you use /svar set variablename playername something, the variable is updated on the database. Could you retry the same test and check if the value on the database is updated? Make sure of that, and then, leave the server A and join server B.

**Comment by Kudosaki** [comment]
Sounds good, will test now

**Comment by Kudosaki** [comment]
![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/6857f607-16f3-4e10-8533-9a0c05c6e2ea)
Before changing on server.

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/546ef352-cc5e-4427-b14c-e66bf83bf33c)
Changed

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/7913de1d-21f1-4488-9b53-5ad5d6176cea)
Still seeing no changes

UUID of player Kudosaki is 4ea416f4-7e12-3cca-83a3-f5b83276ded1

That's my UUID

**Comment by Kudosaki** [comment]
![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/3f776bbf-93c1-4d8a-9056-a5b009de70b3)
Before i changed anything...


Changing on Server B
![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/8d7254e3-0af6-4173-9156-c9d73fa3df55)

/svar get on Server B
![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/0849e5a1-a88f-4068-b5f6-d1f42001addf)

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/5ecd52bb-fe23-41fa-b53b-d2a505f8d6a0)
Database view when changed on server B

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/c888cac3-451a-4ed1-a873-e2963be7dce3)
/svar get on Server A

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/5a18945c-e539-4454-ab19-80237e4881eb)

Setting var on Server A

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/7712f2b0-42b1-4f15-9a0e-26b293ea64bb)
Database when changed var on Server A

![image](https://github.com/Ajneb97/ServerVariables/assets/154644607/b2a7d3a9-a850-4716-82d3-44c30008b5ac)
/svar get going on Server B

**Comment by Kudosaki** [comment]
That whole database thing ain't making lots of senses :lmao:

**Comment by Ajneb97** [comment]
Why do you have the same user with 2 different UUIDs? If that's the case, then it will bug. If you changed the offline-mode of your server while having data, then this will happen. Remove the duplicated usernames.
