### ISSUE TITLE
[Feature Request] New Method for event svar.ajneb97.api.VariableChangeEvent: 'getOldValue()'

### ISSUE THREAD

**Issue by OMarcoGPO** [Ajneb97/ServerVariables#28]
A request a new method that we could use: 'getOldValue()', so it will return the value that a variable had before it was changed.

This could be so useful for some events for your plugin: conditionalevents

**Comment by Ajneb97** [comment]
I'm sure I tried to implement this on an occasion and something was preventing me to make it to work. I will try again when I have the time.

**Comment by OMarcoGPO** [comment]
Thank your for the addition!
