### ISSUE TITLE
Error placeholder

### ISSUE THREAD

**Issue by 0372JesusMtz0372** [Ajneb97/ServerVariables#3]
Ay un problema con el placeholder y es que no puedo obtener el valor de la variable de un jugador en específico, estaría muy bien que lo agregaras o una forma de poder obtener la información

**Comment by Ajneb97** [comment]
Por favor mandame alguna imagen de tu problema y tu config.

**Comment by 0372JesusMtz0372** [comment]
Es que estoy intentando usarlo para deluxe menus si el jugador tiene cierto valor de cierta variable mostrar el item
