### ISSUE TITLE
Added placeholders (Get value player)

### ISSUE THREAD

**Issue by 0372JesusMtz0372** [Ajneb97/ServerVariables#4]
It's missing a couple of important placeholders since they're only there to get the value of the player's variable, but how do I get the value of another player's variable? Add the following option 

```
%servervariables_value_<key>_<player>%
%servervariables_valuedisplay_<key>_<player>%
```

**Comment by Ajneb97** [comment]
For now you can try to use ParseOther expansion from PlaceholderAPI!

**Comment by 0372JesusMtz0372** [comment]
That's true, but I hope you add it one day
